<?php
/**
 * BigCommerceSettingsDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BackOffice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: backoffice-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\BackOffice\Model;

use \ArrayAccess;
use \Aurigma\BackOffice\ObjectSerializer;

/**
 * BigCommerceSettingsDto Class Doc Comment
 *
 * @category Class
 * @description BigCommerce storefront settings.
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BigCommerceSettingsDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BigCommerceSettingsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'access_token' => 'string',
        'big_commerce_client_name' => 'string',
        'api_path' => 'string',
        'big_commerce_client_secret' => 'string',
        'big_commerce_client_id' => 'string',
        'integration_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'access_token' => null,
        'big_commerce_client_name' => null,
        'api_path' => null,
        'big_commerce_client_secret' => null,
        'big_commerce_client_id' => null,
        'integration_name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'access_token' => true,
        'big_commerce_client_name' => true,
        'api_path' => true,
        'big_commerce_client_secret' => true,
        'big_commerce_client_id' => true,
        'integration_name' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_token' => 'accessToken',
        'big_commerce_client_name' => 'bigCommerceClientName',
        'api_path' => 'apiPath',
        'big_commerce_client_secret' => 'bigCommerceClientSecret',
        'big_commerce_client_id' => 'bigCommerceClientId',
        'integration_name' => 'integrationName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_token' => 'setAccessToken',
        'big_commerce_client_name' => 'setBigCommerceClientName',
        'api_path' => 'setApiPath',
        'big_commerce_client_secret' => 'setBigCommerceClientSecret',
        'big_commerce_client_id' => 'setBigCommerceClientId',
        'integration_name' => 'setIntegrationName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_token' => 'getAccessToken',
        'big_commerce_client_name' => 'getBigCommerceClientName',
        'api_path' => 'getApiPath',
        'big_commerce_client_secret' => 'getBigCommerceClientSecret',
        'big_commerce_client_id' => 'getBigCommerceClientId',
        'integration_name' => 'getIntegrationName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('access_token', $data ?? [], null);
        $this->setIfExists('big_commerce_client_name', $data ?? [], null);
        $this->setIfExists('api_path', $data ?? [], null);
        $this->setIfExists('big_commerce_client_secret', $data ?? [], null);
        $this->setIfExists('big_commerce_client_id', $data ?? [], null);
        $this->setIfExists('integration_name', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_token
     *
     * @return string|null
     */
    public function getAccessToken()
    {
        return $this->container['access_token'];
    }

    /**
     * Sets access_token
     *
     * @param string|null $access_token BigCommerce access token.
     *
     * @return self
     */
    public function setAccessToken($access_token)
    {
        if (is_null($access_token)) {
            array_push($this->openAPINullablesSetToNull, 'access_token');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('access_token', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['access_token'] = $access_token;

        return $this;
    }

    /**
     * Gets big_commerce_client_name
     *
     * @return string|null
     */
    public function getBigCommerceClientName()
    {
        return $this->container['big_commerce_client_name'];
    }

    /**
     * Sets big_commerce_client_name
     *
     * @param string|null $big_commerce_client_name BigCommerce client name.
     *
     * @return self
     */
    public function setBigCommerceClientName($big_commerce_client_name)
    {
        if (is_null($big_commerce_client_name)) {
            array_push($this->openAPINullablesSetToNull, 'big_commerce_client_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('big_commerce_client_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['big_commerce_client_name'] = $big_commerce_client_name;

        return $this;
    }

    /**
     * Gets api_path
     *
     * @return string|null
     */
    public function getApiPath()
    {
        return $this->container['api_path'];
    }

    /**
     * Sets api_path
     *
     * @param string|null $api_path BigCommerce API path.
     *
     * @return self
     */
    public function setApiPath($api_path)
    {
        if (is_null($api_path)) {
            array_push($this->openAPINullablesSetToNull, 'api_path');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_path', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_path'] = $api_path;

        return $this;
    }

    /**
     * Gets big_commerce_client_secret
     *
     * @return string|null
     */
    public function getBigCommerceClientSecret()
    {
        return $this->container['big_commerce_client_secret'];
    }

    /**
     * Sets big_commerce_client_secret
     *
     * @param string|null $big_commerce_client_secret BigCommerce client secret.
     *
     * @return self
     */
    public function setBigCommerceClientSecret($big_commerce_client_secret)
    {
        if (is_null($big_commerce_client_secret)) {
            array_push($this->openAPINullablesSetToNull, 'big_commerce_client_secret');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('big_commerce_client_secret', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['big_commerce_client_secret'] = $big_commerce_client_secret;

        return $this;
    }

    /**
     * Gets big_commerce_client_id
     *
     * @return string|null
     */
    public function getBigCommerceClientId()
    {
        return $this->container['big_commerce_client_id'];
    }

    /**
     * Sets big_commerce_client_id
     *
     * @param string|null $big_commerce_client_id BigCommerce client identifier.
     *
     * @return self
     */
    public function setBigCommerceClientId($big_commerce_client_id)
    {
        if (is_null($big_commerce_client_id)) {
            array_push($this->openAPINullablesSetToNull, 'big_commerce_client_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('big_commerce_client_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['big_commerce_client_id'] = $big_commerce_client_id;

        return $this;
    }

    /**
     * Gets integration_name
     *
     * @return string|null
     */
    public function getIntegrationName()
    {
        return $this->container['integration_name'];
    }

    /**
     * Sets integration_name
     *
     * @param string|null $integration_name BigCommerce integration name.
     *
     * @return self
     */
    public function setIntegrationName($integration_name)
    {
        if (is_null($integration_name)) {
            array_push($this->openAPINullablesSetToNull, 'integration_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('integration_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['integration_name'] = $integration_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


