<?php
/**
 * CreateBigCommerceStorefrontDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BackOffice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: backoffice-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\BackOffice\Model;

use \ArrayAccess;
use \Aurigma\BackOffice\ObjectSerializer;

/**
 * CreateBigCommerceStorefrontDto Class Doc Comment
 *
 * @category Class
 * @description BigCommerce storefront creation model.
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateBigCommerceStorefrontDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateBigCommerceStorefrontDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'processing_pipelines_trigger_project_status' => 'int',
        'post_processing_pipeline_id' => 'int',
        'shop_urls' => 'string[]',
        'access_token' => 'string',
        'client_name' => 'string',
        'client_id' => 'string',
        'client_secret' => 'string',
        'integration_name' => 'string',
        'api_path' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'processing_pipelines_trigger_project_status' => 'int32',
        'post_processing_pipeline_id' => 'int32',
        'shop_urls' => null,
        'access_token' => null,
        'client_name' => null,
        'client_id' => null,
        'client_secret' => null,
        'integration_name' => null,
        'api_path' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'processing_pipelines_trigger_project_status' => true,
        'post_processing_pipeline_id' => true,
        'shop_urls' => false,
        'access_token' => false,
        'client_name' => false,
        'client_id' => false,
        'client_secret' => false,
        'integration_name' => false,
        'api_path' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'processing_pipelines_trigger_project_status' => 'processingPipelinesTriggerProjectStatus',
        'post_processing_pipeline_id' => 'postProcessingPipelineId',
        'shop_urls' => 'shopUrls',
        'access_token' => 'accessToken',
        'client_name' => 'clientName',
        'client_id' => 'clientId',
        'client_secret' => 'clientSecret',
        'integration_name' => 'integrationName',
        'api_path' => 'apiPath'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'processing_pipelines_trigger_project_status' => 'setProcessingPipelinesTriggerProjectStatus',
        'post_processing_pipeline_id' => 'setPostProcessingPipelineId',
        'shop_urls' => 'setShopUrls',
        'access_token' => 'setAccessToken',
        'client_name' => 'setClientName',
        'client_id' => 'setClientId',
        'client_secret' => 'setClientSecret',
        'integration_name' => 'setIntegrationName',
        'api_path' => 'setApiPath'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'processing_pipelines_trigger_project_status' => 'getProcessingPipelinesTriggerProjectStatus',
        'post_processing_pipeline_id' => 'getPostProcessingPipelineId',
        'shop_urls' => 'getShopUrls',
        'access_token' => 'getAccessToken',
        'client_name' => 'getClientName',
        'client_id' => 'getClientId',
        'client_secret' => 'getClientSecret',
        'integration_name' => 'getIntegrationName',
        'api_path' => 'getApiPath'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('processing_pipelines_trigger_project_status', $data ?? [], null);
        $this->setIfExists('post_processing_pipeline_id', $data ?? [], null);
        $this->setIfExists('shop_urls', $data ?? [], null);
        $this->setIfExists('access_token', $data ?? [], null);
        $this->setIfExists('client_name', $data ?? [], null);
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('client_secret', $data ?? [], null);
        $this->setIfExists('integration_name', $data ?? [], null);
        $this->setIfExists('api_path', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 256)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 256.";
        }

        if ($this->container['shop_urls'] === null) {
            $invalidProperties[] = "'shop_urls' can't be null";
        }
        if ($this->container['access_token'] === null) {
            $invalidProperties[] = "'access_token' can't be null";
        }
        if ($this->container['client_name'] === null) {
            $invalidProperties[] = "'client_name' can't be null";
        }
        if ($this->container['client_id'] === null) {
            $invalidProperties[] = "'client_id' can't be null";
        }
        if ($this->container['client_secret'] === null) {
            $invalidProperties[] = "'client_secret' can't be null";
        }
        if ($this->container['integration_name'] === null) {
            $invalidProperties[] = "'integration_name' can't be null";
        }
        if ($this->container['api_path'] === null) {
            $invalidProperties[] = "'api_path' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Storefront name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 256)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CreateBigCommerceStorefrontDto., must be smaller than or equal to 256.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets processing_pipelines_trigger_project_status
     *
     * @return int|null
     */
    public function getProcessingPipelinesTriggerProjectStatus()
    {
        return $this->container['processing_pipelines_trigger_project_status'];
    }

    /**
     * Sets processing_pipelines_trigger_project_status
     *
     * @param int|null $processing_pipelines_trigger_project_status Status of project that should become a trigger to start project items processing automatically.
     *
     * @return self
     */
    public function setProcessingPipelinesTriggerProjectStatus($processing_pipelines_trigger_project_status)
    {
        if (is_null($processing_pipelines_trigger_project_status)) {
            array_push($this->openAPINullablesSetToNull, 'processing_pipelines_trigger_project_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('processing_pipelines_trigger_project_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['processing_pipelines_trigger_project_status'] = $processing_pipelines_trigger_project_status;

        return $this;
    }

    /**
     * Gets post_processing_pipeline_id
     *
     * @return int|null
     */
    public function getPostProcessingPipelineId()
    {
        return $this->container['post_processing_pipeline_id'];
    }

    /**
     * Sets post_processing_pipeline_id
     *
     * @param int|null $post_processing_pipeline_id Identifier of pipeline that should be used for post-processing for projects when all project items are processed.
     *
     * @return self
     */
    public function setPostProcessingPipelineId($post_processing_pipeline_id)
    {
        if (is_null($post_processing_pipeline_id)) {
            array_push($this->openAPINullablesSetToNull, 'post_processing_pipeline_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('post_processing_pipeline_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['post_processing_pipeline_id'] = $post_processing_pipeline_id;

        return $this;
    }

    /**
     * Gets shop_urls
     *
     * @return string[]
     */
    public function getShopUrls()
    {
        return $this->container['shop_urls'];
    }

    /**
     * Sets shop_urls
     *
     * @param string[] $shop_urls List of shops URLs.
     *
     * @return self
     */
    public function setShopUrls($shop_urls)
    {
        if (is_null($shop_urls)) {
            throw new \InvalidArgumentException('non-nullable shop_urls cannot be null');
        }
        $this->container['shop_urls'] = $shop_urls;

        return $this;
    }

    /**
     * Gets access_token
     *
     * @return string
     */
    public function getAccessToken()
    {
        return $this->container['access_token'];
    }

    /**
     * Sets access_token
     *
     * @param string $access_token BigCommerce access token.
     *
     * @return self
     */
    public function setAccessToken($access_token)
    {
        if (is_null($access_token)) {
            throw new \InvalidArgumentException('non-nullable access_token cannot be null');
        }
        $this->container['access_token'] = $access_token;

        return $this;
    }

    /**
     * Gets client_name
     *
     * @return string
     */
    public function getClientName()
    {
        return $this->container['client_name'];
    }

    /**
     * Sets client_name
     *
     * @param string $client_name BigCommerce client name.
     *
     * @return self
     */
    public function setClientName($client_name)
    {
        if (is_null($client_name)) {
            throw new \InvalidArgumentException('non-nullable client_name cannot be null');
        }
        $this->container['client_name'] = $client_name;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string $client_id BigCommerce client identifier.
     *
     * @return self
     */
    public function setClientId($client_id)
    {
        if (is_null($client_id)) {
            throw new \InvalidArgumentException('non-nullable client_id cannot be null');
        }
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets client_secret
     *
     * @return string
     */
    public function getClientSecret()
    {
        return $this->container['client_secret'];
    }

    /**
     * Sets client_secret
     *
     * @param string $client_secret BigCommerce client secret.
     *
     * @return self
     */
    public function setClientSecret($client_secret)
    {
        if (is_null($client_secret)) {
            throw new \InvalidArgumentException('non-nullable client_secret cannot be null');
        }
        $this->container['client_secret'] = $client_secret;

        return $this;
    }

    /**
     * Gets integration_name
     *
     * @return string
     */
    public function getIntegrationName()
    {
        return $this->container['integration_name'];
    }

    /**
     * Sets integration_name
     *
     * @param string $integration_name BigCommerce integration name.
     *
     * @return self
     */
    public function setIntegrationName($integration_name)
    {
        if (is_null($integration_name)) {
            throw new \InvalidArgumentException('non-nullable integration_name cannot be null');
        }
        $this->container['integration_name'] = $integration_name;

        return $this;
    }

    /**
     * Gets api_path
     *
     * @return string
     */
    public function getApiPath()
    {
        return $this->container['api_path'];
    }

    /**
     * Sets api_path
     *
     * @param string $api_path BigCommerce API path.
     *
     * @return self
     */
    public function setApiPath($api_path)
    {
        if (is_null($api_path)) {
            throw new \InvalidArgumentException('non-nullable api_path cannot be null');
        }
        $this->container['api_path'] = $api_path;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


