<?php
/**
 * ProductVariantAvailabilityDtoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BackOffice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: backoffice-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\BackOffice\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductVariantAvailabilityDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Parameters for setting product variants availability.
 * @package     Aurigma\BackOffice
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductVariantAvailabilityDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductVariantAvailabilityDto"
     */
    public function testProductVariantAvailabilityDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "availability"
     */
    public function testPropertyAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "variant_uids"
     */
    public function testPropertyVariantUids()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
