<?php
/**
 * ProductReferencesManagementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BackOffice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: backoffice-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\BackOffice\Test\Api;

use \Aurigma\BackOffice\Configuration;
use \Aurigma\BackOffice\ApiException;
use \Aurigma\BackOffice\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductReferencesManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductReferencesManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productReferencesManagementCreate
     *
     * Creates a new storefront product reference..
     *
     */
    public function testProductReferencesManagementCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesManagementDelete
     *
     * Deletes the storefront product reference..
     *
     */
    public function testProductReferencesManagementDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesManagementGet
     *
     * Returns a storefront product reference..
     *
     */
    public function testProductReferencesManagementGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesManagementGetAll
     *
     * Returns all storefront product references relevant to the specified query parameters..
     *
     */
    public function testProductReferencesManagementGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
