<?php
/**
 * UsersManagementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BackOffice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: backoffice-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\BackOffice\Test\Api;

use \Aurigma\BackOffice\Configuration;
use \Aurigma\BackOffice\ApiException;
use \Aurigma\BackOffice\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\BackOffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for usersManagementCreate
     *
     * Creates a new tenant user..
     *
     */
    public function testUsersManagementCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersManagementDelete
     *
     * Deletes an existing tenant user..
     *
     */
    public function testUsersManagementDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersManagementGet
     *
     * Returns a tenant user by user identifier..
     *
     */
    public function testUsersManagementGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersManagementGetAll
     *
     * Returns a tenant users list..
     *
     */
    public function testUsersManagementGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersManagementGetAllRoles
     *
     * Returns all tenant user roles, relevant to the specified query parameters..
     *
     */
    public function testUsersManagementGetAllRoles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
